apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy215
  labels:
    app: autodeploy215
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717258074126
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy215
  template:
    metadata:
      labels:
        app: autodeploy215
    spec:
      containers:
        - name: autodeploy215
          image: acrworkflow1717258074126.azurecr.io/image-workflow-1717258074126:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
